import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import AppProvider from '@/provider/appProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          {children}
          {/* <div className="w-full h-auto">
            <div className="absolute top-20 left-0 w-full h-[100px] bg-gradient-to-r from-blue-500 to-purple-500 blur-[150px] transform rotate-45"></div>
          </div> */}
        </AppProvider>
      </body>
    </html>
  );
}
